--- #YAML:1.0
name:               Bot-BasicBot-Pluggable-Module-XKCD
version:            0.06
abstract:           Get xkcd comic links and titles
author:
    - Josh Holland <jrh@joshh.co.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::Simple:  0
    Test::More:   0
    URI::Title:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
